name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  DeployDev:
    name: Deploy to dev
    if: githut.event_name == "pull_request"
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Developement
      url: 'http://dev.mytestapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
  DeployStaging:
    name: Deploy to staging
    if: githut.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
  DeployProd:
    name: Deploy to production
    if: githut.event.ref == 'refs/heads/main'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
